### ISSUE TITLE
How to utilize Cloud Build cache of Docker build

### ISSUE THREAD

**Issue by galah92** [jgunnink/rustless_webserver_demo#2]
Hi, quick question:
Assume I build & deploy this code, then change something a redeploy again. I expected Cloud Build to be able to cache the build steps, specifically the fetching & building of all the 3rd party crates specified in `Cargo.toml`, but seems like Cloud Build doesn't pick that up by default.
How can I enable that?

Thank you

**Comment by jgunnink** [comment]
Hey there!

Cloud build doesn't have a cache by default. I think the intent of cloud build is to reliably reproduce builds and caching can introduce all kinds of unexpected side effects.

With that said, if you're building a docker image, you can make use of Docker's `--cache-from` CLI arg to pull in an image that you've built before, and try to reuse some layers of the image in your current build.

You would need to reorder the dockerfile and use different commands in the build process than the ones outlined in this demo, though.

**Comment by galah92** [comment]
Thank you for the response! Any chance to add a working example for that? I tried using `--cache-from` but it didn't seem to pick up the relevant layers correctly. It seems relevant for an example for Rust-over-Cloud-Run.

**Comment by jgunnink** [comment]
I don't have a rust example, but I did write a blogpost about doing it with Ruby & Rails where it cached the downloading and installing all the gems. Perhaps you can adapt it for your needs.

Link: https://jgunnink.substack.com/p/using-cloudbuild-github-ci
